# Generated by Django 5.0.1 on 2024-02-06 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='BookingDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
    ]
