# Generated by Django 5.0.1 on 2024-02-06 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 6, 17, 45, 18, 894964, tzinfo=datetime.timezone.utc)),
        ),
    ]
